# ~/.config/starship.toml

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[username]
disabled = false
show_always = true
format = '[$user]($style) '
style_user = "yellow"

[directory]
truncation_length = 3
truncate_to_repo = false
truncation_symbol = '…/'

[git_branch]
truncation_length = 20
# remove the 'on' conjunction
format = '[$symbol$branch]($style) '

[git_state]
disabled = false

[git_status]
disabled = false

[time]
disabled = false
format = '🕙 [$time]($style) '
time_format = '%T'

[nodejs]
disabled = false
